### ISSUE TITLE
Depth and elevation are not very intuitive 

### ISSUE THREAD

**Issue by guidomeijer** [VirtualBrainLab/Pinpoint#168]
In the help menu the picture on the right shows that depth is the movement of the probe along it's own axis. However, the controls list depth as Z/X, these buttons control the movement in the DV plane which is something different. Intuitively I would say that "depth" refers to the movement of the probe along it's own axis (like in the picture). Then the control list T/G as "elevation" but these buttons control where the contact sites are on the probe (but don't actually move the probe). I would think that elevation would refer to movement in the DV plane (what Z/X now controls).

Tested on the web app (http://data.virtualbrainlab.org/Pinpoint/).

**Comment by dbirman** [comment]
Fixed w/ cc5ca2de1be714a5fdf2809c21343703bdfda706, will get pushed out in v0.8.0 coming this week
