### ISSUE TITLE
Cannot move craniotomies anterior to Bregma

### ISSUE THREAD

**Issue by BlakeRussell98** [VirtualBrainLab/Pinpoint#235]

**Comment by dbirman** [comment]
Thanks for flagging that. Looks like the craniotomy controls got messed up in a recent update -- the coordinates also need some updated controls. I'll have that fixed in the next major release.

**Comment by dbirman** [comment]
Movements now fixed with e2690a3016d7530a440804db9a1a74e7892868a2, but still need to implement CoordinateSpace transforms correctly

**Comment by dbirman** [comment]
CoordinateSpace/Transform implemented correctly. Deploying with 0.8.4 2abfced7deebe2d3cd5af3a92fbe91584825d310
