### ISSUE TITLE
Adding probes other than neuropixels 

### ISSUE THREAD

**Issue by elladulko** [VirtualBrainLab/Pinpoint#278]
Hi Dan! I saw that the Pinpoint is live! Congrats! 
Are you planning on adding more types of probes? Our lab (as well as many other labs) is currently using UCLA probes and Cambridge Neurotech. 
Kind Regards,
Ela

**Comment by dbirman** [comment]
Hi Ela -- yes we do plan to add more probes, I'll be working on this in a few months. If you want it to happen sooner I can add them very easily but I don't have the time to generate the 3d models myself. If you can provide me with the 3D model file then I can put it into Pinpoint in the next release. 

For the 3D model: the file needs to be tip-referenced (i.e. the origin (0,0,0) coordinate in the 3D model needs to be at the tip) and I also need to know where the recording sites are relative to the tip (e.g. for neuropixels probes the tip is at height 0, the electrode sites start at 200 um, and go up to 10,200 um). If the channels are selectable like on the Neuropixel probe we can also make it possible to move the recording region, or we can just fix it for the whole length of the probe.

Let me know if that makes sense? I'll have more time to add 3D models myself later this year, but right now the best I can do is add models if you can provide them.

**Comment by dbirman** [comment]
Closing this for now since I haven't gotten any additional info. @elladulko if you're still interested in adding additional UCLA probes we currently have the 128L and 256F probes in Pinpoint and could definitely add more.
