### ISSUE TITLE
Brain/skull scaling

### ISSUE THREAD

**Issue by BlakeRussell98** [VirtualBrainLab/Pinpoint#291]
Would it be possible to implement a feature whereby if Pinpoint is given the distance between Bregma and Lambda, it can scale the size of the brain and skull rig appropriately?
Thanks,
Blake

**Comment by dbirman** [comment]
Yeah this is on the to-do list. I'll bump it a little higher in priority!

**Comment by dbirman** [comment]
- [ ] base b-l distance in MRI transform 4.15mm
- [ ] add relative input / scale system

**Comment by dbirman** [comment]
3875056f8aa6ae6df4600c6f1c0a881219b8b68a

**Comment by dbirman** [comment]
Skull scaling delayed to 1.0.X

- [ ] Add skull rig scaling when active, or warn users that skull rig does not get scaled

**Comment by dbirman** [comment]
Closing for now, rig scaling will come later
