### ISSUE TITLE
Tutorials page NOT working

### ISSUE THREAD

**Issue by taningh86** [VirtualBrainLab/Pinpoint#306]
Hi,
The tutorials page is showing a 404 error code. 

Thanks
Jimmy

**Comment by dbirman** [comment]
Page is working for me: https://virtualbrainlab.org/pinpoint/tutorial.html

What link did you click to get to the page, we might have a dead link somewhere?

**Comment by taningh86** [comment]
Hi Dan,
Yeah, the tutorials link on the page did not work but the tuturials tab on the side bar worked. 

Jimmy

**Comment by dbirman** [comment]
Got it thanks!

Fixed with e5328c466e0447b64136a0a8e1dc7b40b973643e
