### ISSUE TITLE
'new probe' could include fiber and micropipette

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/Pinpoint#357]
A very quick way to expand the user-base could be to add optical fibers (literally just a big white cylinder) and micropipettes (a big white cylinder that tapers to a point) as options in the 'add a new probe' menu. This would allow people to use the tool for planning virus injections and fiber implants. Probably there is no current tool that they can do this with where the planning is in MRI-atlas space and option exists for scaling by bregma-lambda (in addition to of course all the features). This occurred to me when I was showing pinpoint to a collaborator (Mike Schwartz) who was super-impressed but I realized there was not too much value in sending him the link since no one in his lab does neuropixels - but they probably would use it if it felt to them like it was an appropriate tool for planning injections/fibers. 

For the optical fiber you probably want to be able to set the diameter, is the only complication. Maybe one simple way to do this would be to have a single new selection called something like "Generic" (or "Fiber/pipette"?) where you can set a diameter of 25 µm (the default) to get basically a very generic single-shank "probe" that's like a pipette or like a single-shank probe that's not neuropixels, or you can set the diameter to be 200 um or whatever and you've got a fiber. The coordinates should point to the center of the cylinder, at the bottom face.

**Comment by dbirman** [comment]
I'm adding both of these now but some small clarification is needed. Is the *only* coordinate people care about the tip coordinate?

And then for sizes, it's a pain right now to swap the 3D model for a different one after a probe is in the scene, something to refactor later maybe. It's trivial though to just add a whole bunch of new probe types with different models. Would diameter = [25,50,100,200um] be a reasonable range to have available?

**Comment by dbirman** [comment]
25um added on b3a178e3dce3c8885be45bb9d7dd6b9c6618e146

**Comment by nsteinme** [comment]
I guess it is like a neuropixels probe: they care about the tip because that's where their target is, and they care about the insertion point because they need to make a craniotomy there. Most of the time injections are done straight down because there's no other equipment to avoid, but sometimes you go in at an angle to avoid a blood vessel or something. 

Up to you, but what about having a little selection box pop up with a slider and a text field to set the diameter when you create it? I can see it being useful to change the diameter within the scene, if you are trying to see what structures you'd hit with one diameter fiber or another, by the way. I guess what the user would manually do to work this out is write down the coordinates, delete the probe, add a new one with new diameter, and re-enter the coords. Perhaps that sequence could be done automatically (i.e. you end up with a probe of new diameter, but how you got there is invisible to the user and it didn't actually involve changing properties of the existing probe)?

**Comment by dbirman** [comment]
I think this suggests that I need a new system where you can swap 3D models without losing the coordinates of an insertion, so for now these will be fixed sizes but in the future I will make this "swap models" feature possible

**Comment by dbirman** [comment]
all pipettes added d859b63c94610b2f66cd014f0a60536d30c83b1a

This will get pushed out in v0.9 coming very soon, and then we can forward to your colleague

**Comment by nsteinme** [comment]
Great!

**Comment by Andrianarivelo** [comment]
Hello, this is an amazing feature and we would like to use pinpoint in my lab to plan trajectories for stereotaxic injections. I'm using the desktop app on windows 10, when adding a pipette and pointing to a target or moving the pipette the coordinates doesn't update also the coronal view disappeared, any idea why ? With a neuropixel probe we don't have this issue
![no_coordinates](https://github.com/VirtualBrainLab/Pinpoint/assets/70333713/f6163634-d33a-4e3c-ba34-8d510362b971)

**Comment by dbirman** [comment]
@Andrianarivelo Thanks for reporting this -- I believe I caught this bug a few weeks ago and have it fixed in the next release, should be out later this week. Sorry about the delay, we were at SfN and that slowed things down for a bit!
