### ISSUE TITLE
text not very readable in search box when set to full names

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/Pinpoint#383]
I see this - maybe just a smaller font size would be fine? 

![image](https://github.com/VirtualBrainLab/Pinpoint/assets/7590975/7d6b5d42-13f6-4c9a-bbdc-8ad043e2e220)

**Comment by dbirman** [comment]
Fixed in the next release https://github.com/VirtualBrainLab/Pinpoint/issues/372
