### ISSUE TITLE
Backspace not deleting probes, possibly related to SpikeGLX connection?

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/Pinpoint#429]
From JC: I can’t figure out how to delete any probes from the 3D view. Selecting the shanks on the left and hitting backspace deletes them from that shank view, but the 3D view doesn’t update, nor does the list of selectable probes in the API dialog. Deleting the experiments that contained these probes also doesn’t remove them.

**Comment by kjy5** [comment]
See if c1be0c873ba5479d76c82dba6bde9ef95faa1f0a helped
