### ISSUE TITLE
Null pointer when removing probes

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/Pinpoint#432]
The async code is still running during a probe destroy event... need to cancel or ignore it after the probe gets destroyed

**Comment by dbirman** [comment]
FYI: there's a "probe added or removed event" that triggers off of TPManager that you might want to subscribe to for this kind of thing!

**Comment by kjy5** [comment]
Thanks! I'll take a look at this. I was using the Destroy and OnDestroy methods but those didn't seem to work. Do you know if those events trigger before/after Destroy happens?

**Comment by dbirman** [comment]
If you're using OnDestroy there could be a garbage collector issue, OnDestroy isn't guaranteed to fire at any particular time. The ProbeManager.Destroy() function that I added does get called right before we call Destroy(probe), so that should be fine to trigger this kind of stuff

**Comment by dbirman** [comment]
Ah I see -- this bug: https://github.com/VirtualBrainLab/Pinpoint/issues/429 is caused by this null pointer issue. Let me know when you push a fix so that I can push a new build out ASAP, this is on the 0.9.1 release unfortunately, which is going to cause a lot of grief if anybody tries to use it!

**Comment by kjy5** [comment]
oops. Let me get onto that.

**Comment by kjy5** [comment]
#433
