### ISSUE TITLE
export/reload function?

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/Pinpoint#49]
Would be great to have some kind of save/load functionality - I guess it would just save a text file with the coordinates of all probes, perhaps also with some metadata about the graphical display, like which areas are rendered in 3D, and which rig(s) are shown? Then you could just select that file and get back to where you were.

**Comment by dbirman** [comment]
Closing with #78, splitting out rigs into https://github.com/VirtualBrainLab/Pinpoint/issues/259
