### ISSUE TITLE
some areas not accessible for 3d highlighting

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/Pinpoint#66]
when you search for an acronym, it pulls up the first eight areas it finds that include those letters. But this doesn't always result in the area you want - e.g. typing "PL" shows "CTXspl" and "VISpl1" and others, but doesn't actually show PL. Same for "VI". Maybe the easiest quick solution is to make it first list any exact matches and only then list the ones returned on the current search. A more general solution that would also solve the problem of some people not knowing the acronyms of all areas might be to let users also search by the area name, not just the acronym. I also really like the hierarchical area browser where you can click Isocortex->PL->PL2/3 or whatever.

**Comment by dbirman** [comment]
- [ ] Improve searching to allow searching by name OR area regardless of whether the acronym setting is turned on
- [ ] Add a hierarchy window attached to the search, or replace the search results window with a hierarchy view

**Comment by dbirman** [comment]
Generic search added in v0.7.0

**Comment by dbirman** [comment]
#169

**Comment by dbirman** [comment]
Fixing through BrainAtlas
